"""Take the App Store screenshots in a simulator, in ten languages.

    python store/shoot.py                 # every language
    python store/shoot.py --locale fr-FR  # one
    python store/shoot.py --no-maps       # skip the Apple Maps payoff shot

macOS only — it drives `xcrun simctl`. Run from the repo root.

Why this exists. Screenshots used to be taken by hand on a phone, which meant
they were in English, at that phone's size (an iPhone 16 Pro shoots 1206x2622
and the App Store wants 1290x2796), and had to be retaken from nothing for a
one-word change. One person in the loop caused all three problems.

The three things this script is careful about, each learned the hard way:

  * **Size is verified, not assumed.** Simulator names move between Xcode
    versions, so rather than trusting "iPhone 16 Plus" to be 1290x2796 it takes
    a screenshot and reads the dimensions out of the PNG header. A wrong device
    fails here rather than at upload with IMAGE_INCORRECT_DIMENSIONS. This is
    not hypothetical: **Xcode 26 ships no 6.7-inch iPhone at all**, so the size
    the App Store still demands cannot be produced natively any more and the
    images are downscaled from 1320x2868 instead. See [boot_simulator].
  * **A blank or duplicated frame fails the run.** The specific disaster is a
    run that photographs the home screen six times because the app crashed on
    launch, verifies nothing, uploads, and reports success. Every image is
    checked for being near-uniform, and every pair within a locale for being
    identical.
  * **Nothing is skipped silently.** If the Maps shot cannot be produced the
    script says so, by name, and says what the localised set will contain
    instead.

The status bar is overridden rather than cleaned up afterwards. `simctl status_bar
override` gives Apple's own 9:41 with full bars, which is both what Apple's own
screenshots use and the end of the "<- TestFlight" label that had to be painted
out of the hand-taken set.
"""
import argparse
import hashlib
import json
import pathlib
import shutil
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
SHOTS = HERE / "screenshots"
BUNDLE = "com.spencerfields.littlebird"
SLOT = "APP_IPHONE_67"
# Apple accepts either of these for the 6.7-inch slot. Whichever the chosen
# simulator produces is used, and every image in the run must then match it —
# a set of mixed sizes is rejected at upload.
WANT = [(1290, 2796), (1284, 2778)]

# The scenes, in product-page order. Must match `sceneNames` in
# lib/src/screenshots.dart — the test scene_render_test.dart renders every one
# of them, so a name that exists here and not there fails the suite.
SCENES = [
    "01-the-list",
    "02-add-to-a-guide",
    "03-correct-a-place",
    "04-which-city",
    "05-places-kept",
    "06-a-little-bird",
]

# The Apple Maps payoff shot, taken by opening a real guide link. Not a Flutter
# scene — it is Apple's own app, which is the point of it.
MAPS_SCENE = "07-in-apple-maps"

# A guide of five real London places. Generated by `dart run
# tool/guide_link.dart`, never typed: it is a base64 protobuf, so a hand-written
# one would be plausible, wrong, and open as an empty guide that nobody notices
# until the store page is live. Regenerate if the fixtures change.
GUIDE_URL = (
    "https://maps.apple.com/guide?_col="
    "Cg9Mb25kb24sIE9jdG9iZXISIwiuTRC1rNetnKaJ%2FUMaACoSRGlzaG9vbSBTaG9yZWRpdG"
    "NoEiAIrk0QkZCou9m6u69lGgAqD1dyaWdodCBCcm90aGVycxIaCK5NEOKh1v2l7pj%2FlAEa"
    "ACoIRWxsaW90J3MSGAiuTRD2vP7rzMqx31IaACoHQXJhYmljYRIdCK5NEOC79q2J9ry9ExoA"
    "KgxCbGFjayAmIEJsdWU%3D"
)

# The ten most-spoken languages worldwide, as (App Store Connect locale,
# AppleLanguages value, AppleLocale value). English is shot too: the hand-taken
# set is a different size and this one replaces it.
SHOOT = [
    ("en-GB", "en-GB", "en_GB"),
    ("zh-Hans", "zh-Hans", "zh_CN"),
    ("hi", "hi", "hi_IN"),
    ("es-ES", "es-ES", "es_ES"),
    ("fr-FR", "fr-FR", "fr_FR"),
    ("ar-SA", "ar", "ar_SA"),
    ("bn-BD", "bn", "bn_BD"),
    ("pt-BR", "pt-BR", "pt_BR"),
    ("ru", "ru", "ru_RU"),
    ("id", "id", "id_ID"),
]

# Preferred first, but NOT a closed list. A hardcoded list failed on macos-26
# because none of the six names existed there, so every available iPhone is
# enumerated and probed and these merely go first.
PREFERRED = ("Plus", "Pro Max", "Max")


def check_scenes_agree():
    """Fails if SCENES here has drifted from `sceneNames` in the Dart source.

    Two lists of the same thing in two languages will diverge. A name here that
    the app does not know renders the "no scene called…" placeholder, which the
    uniformity check would catch; a name in Dart that is missing here is worse,
    because it just quietly never gets photographed and the set is short by one
    with nothing to show why.
    """
    src = (ROOT / "lib/src/screenshots.dart").read_text(encoding="utf-8")
    block = src.split("const sceneNames = <String>[", 1)
    if len(block) != 2:
        sys.exit("could not find sceneNames in lib/src/screenshots.dart")
    import re
    names = re.findall(r"'([^']+)'", block[1].split("];", 1)[0])
    if names != SCENES:
        sys.exit("SCENES in this file and sceneNames in screenshots.dart "
                 f"disagree:\n  here: {SCENES}\n  dart: {names}")


def run(*args, check=True, quiet=False):
    r = subprocess.run(args, capture_output=True, text=True)
    if check and r.returncode != 0:
        sys.exit(f"failed: {' '.join(args)}\n{r.stderr.strip()}")
    if not quiet and r.stderr.strip():
        print(f"  ! {r.stderr.strip()[:200]}")
    return r


def png_size(path):
    """Width and height out of the IHDR. No image library needed for this bit."""
    with path.open("rb") as f:
        head = f.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    return (int.from_bytes(head[16:20], "big"),
            int.from_bytes(head[20:24], "big"))


def iphones():
    """Every available iPhone simulator, most promising first."""
    r = run("xcrun", "simctl", "list", "devices", "available", "-j", quiet=True)
    try:
        data = json.loads(r.stdout)
    except json.JSONDecodeError:
        sys.exit("could not read `simctl list devices -j`")
    found = []
    for runtime, devices in (data.get("devices") or {}).items():
        if "iOS" not in runtime:
            continue
        for d in devices:
            if not d.get("isAvailable", True) or "iPhone" not in d.get("name", ""):
                continue
            found.append((d["name"], d["udid"]))
    found.sort(key=lambda nu: (
        0 if any(x in nu[0] for x in PREFERRED) else 1, nu[0]))
    return found


def creatable_sixty_sevens():
    """Device TYPES Xcode knows that might shoot 6.7-inch, even if none exists.

    The runner pre-creates a handful of devices; Xcode usually knows more types
    than it instantiates. Worth trying before resorting to scaling, because a
    native screenshot beats a resampled one.
    """
    r = run("xcrun", "simctl", "list", "devicetypes", "-j", quiet=True)
    try:
        types = json.loads(r.stdout).get("devicetypes") or []
    except json.JSONDecodeError:
        return []
    wanted = ("iPhone 16 Plus", "iPhone 15 Plus", "iPhone 14 Plus",
              "iPhone 15 Pro Max", "iPhone 14 Pro Max", "iPhone 16 Pro Max")
    out = []
    for name in wanted:
        for t in types:
            if t.get("name") == name:
                out.append((name, t["identifier"]))
                break
    return out


def newest_runtime():
    r = run("xcrun", "simctl", "list", "runtimes", "-j", quiet=True)
    try:
        runtimes = json.loads(r.stdout).get("runtimes") or []
    except json.JSONDecodeError:
        return None
    ios = [rt for rt in runtimes
           if rt.get("isAvailable") and "iOS" in rt.get("name", "")]
    return ios[-1]["identifier"] if ios else None


def measure(udid):
    """Boot a device and report what its screenshots actually measure."""
    run("xcrun", "simctl", "boot", udid, check=False, quiet=True)
    run("xcrun", "simctl", "bootstatus", udid, "-b", check=False, quiet=True)
    probe = SHOTS / "_probe.png"
    probe.parent.mkdir(parents=True, exist_ok=True)
    run("xcrun", "simctl", "io", udid, "screenshot", "--type=png", str(probe),
        check=False, quiet=True)
    size = png_size(probe) if probe.exists() else None
    probe.unlink(missing_ok=True)
    return size


def boot_simulator():
    """A simulator to shoot on, and the size the images must end up.

    Three routes, best result first:

      1. A device that already shoots a size the App Store accepts.
      2. A 6.7-inch device TYPE Xcode knows, created on the spot.
      3. The largest device available, with the images scaled afterwards.

    Route 3 exists because Xcode 26 ships **no** 6.7-inch iPhone at all — the
    lineup measures 1320x2868, 1260x2736, 1206x2622 and 1170x2532 — while the
    App Store's largest iPhone slot is still APP_IPHONE_67 at 1290x2796,
    confirmed against the live API on 17 August 2026. No device satisfies it any
    more, so something has to be resampled, and a 1320x2868 downscale is the
    closest available: 0.24% of aspect drift, which is invisible.
    """
    candidates = iphones()
    if not candidates:
        sys.exit("no iPhone simulators are available on this runner")
    print(f"{len(candidates)} iPhone simulators available; want "
          f"{' or '.join(f'{w}x{h}' for w, h in WANT)}")

    tried, seen = [], set()
    for name, udid in candidates:
        if name in seen:
            continue
        seen.add(name)
        size = measure(udid)
        tried.append((name, size))
        if size in WANT:
            print(f"native: {name} at {size[0]}x{size[1]}")
            return udid, size, size
        run("xcrun", "simctl", "shutdown", udid, check=False, quiet=True)

    print("\nno device shoots it natively:")
    for name, size in tried:
        print(f"  {name:<24} {size}")

    runtime = newest_runtime()
    for name, identifier in creatable_sixty_sevens():
        if runtime is None:
            break
        print(f"\ncreating {name} to try for a native size...")
        made = run("xcrun", "simctl", "create", "wren-shots", identifier,
                   runtime, check=False, quiet=True)
        udid = made.stdout.strip()
        if not udid:
            print(f"  could not create {name}")
            continue
        size = measure(udid)
        if size in WANT:
            print(f"native: {name} at {size[0]}x{size[1]} (created)")
            return udid, size, size
        print(f"  {name} shoots {size} - not it")
        run("xcrun", "simctl", "shutdown", udid, check=False, quiet=True)
        run("xcrun", "simctl", "delete", udid, check=False, quiet=True)

    biggest = max((t for t in tried if t[1]), key=lambda t: t[1][0] * t[1][1],
                  default=None)
    if biggest is None:
        sys.exit("no simulator produced a screenshot at all")
    name, native = biggest
    udid = next(u for n, u in candidates if n == name)
    target = min(WANT, key=lambda w: abs(w[0] / w[1] - native[0] / native[1]))
    drift = abs((native[0] / native[1]) - (target[0] / target[1]))
    drift = drift / (target[0] / target[1])
    if drift > 0.01:
        sys.exit(
            f"the closest device is {name} at {native[0]}x{native[1]}, which is "
            f"{drift:.1%} off {target[0]}x{target[1]} in aspect ratio. Scaling "
            f"that would visibly distort or letterbox the images, and a padded "
            f"store screenshot looks like a mistake, so this stops here.")
    print(f"\nscaling: {name} shoots {native[0]}x{native[1]}; images will be "
          f"resampled to {target[0]}x{target[1]} ({drift:.2%} aspect drift)")
    measure(udid)
    return udid, native, target


def scale_to(path, target):
    """Resample one screenshot to the size the App Store wants.

    LANCZOS, and only ever downwards - upscaling invents detail a reviewer can
    see. Overwritten in place, because a directory holding two sizes is a
    directory something uploads the wrong one from.
    """
    from PIL import Image
    with Image.open(path) as im:
        if im.size == tuple(target):
            return
        out = im.convert("RGB").resize(tuple(target), Image.LANCZOS)
    out.save(path, "PNG", optimize=True)


def set_language(udid, language, locale):
    """Sets the whole device's language, not just the app's.

    Per-process `-AppleLanguages` would localise Wren, but the Apple Maps shot
    needs Maps and the map's own labels localised too, and those belong to the
    device. Written before the app is launched, and the app is passed the same
    values on launch as well, because the two mechanisms disagree occasionally
    and agreeing with itself is cheap.
    """
    run("xcrun", "simctl", "spawn", udid, "defaults", "write",
        "Apple Global Domain", "AppleLanguages", "-array", language,
        check=False)
    run("xcrun", "simctl", "spawn", udid, "defaults", "write",
        "Apple Global Domain", "AppleLocale", "-string", locale, check=False)
    # A respring, so anything already running picks the new language up.
    run("xcrun", "simctl", "spawn", udid, "launchctl", "stop",
        "com.apple.SpringBoard", check=False)
    run("xcrun", "simctl", "bootstatus", udid, "-b", check=False)


def clean_status_bar(udid):
    run("xcrun", "simctl", "status_bar", udid, "override",
        "--time", "9:41",
        "--dataNetwork", "wifi", "--wifiMode", "active", "--wifiBars", "3",
        "--cellularMode", "active", "--cellularBars", "4",
        "--batteryState", "charged", "--batteryLevel", "100", check=False)


def uniformity(path):
    """How flat the image is, 0 (varied) to 1 (one colour).

    The failure this catches: the app died on launch and every screenshot is of
    the simulator's home screen or a black frame. Uploading six of those and
    reporting success is the worst outcome available to this script.
    """
    from PIL import Image
    with Image.open(path) as im:
        small = im.convert("RGB").resize((64, 138))
        colours = small.getcolors(maxcolors=64 * 138) or []
    if not colours:
        return 1.0
    total = sum(c for c, _ in colours)
    return max(c for c, _ in colours) / total


def difference(a, b):
    """Mean absolute pixel difference between two images, 0 to 255."""
    from PIL import Image, ImageChops, ImageStat
    with Image.open(a) as ia, Image.open(b) as ib:
        x = ia.convert("RGB").resize((128, 277))
        y = ib.convert("RGB").resize((128, 277))
        stat = ImageStat.Stat(ImageChops.difference(x, y))
    return sum(stat.mean) / len(stat.mean)


def shoot_app(udid, out_dir, language, locale, settle):
    """One launch per scene, so one build covers every scene and language."""
    taken = []
    for scene in SCENES:
        out = out_dir / f"{scene}.png"
        run("xcrun", "simctl", "terminate", udid, BUNDLE, check=False,
            quiet=True)
        env = {"SIMCTL_CHILD_WREN_SCENE": scene}
        cmd = ["xcrun", "simctl", "launch", udid, BUNDLE,
               "-AppleLanguages", f"({language})", "-AppleLocale", locale]
        r = subprocess.run(cmd, capture_output=True, text=True,
                           env={**_environ(), **env})
        if r.returncode != 0:
            sys.exit(f"launch failed for {scene}: {r.stderr.strip()}")
        _sleep(settle)
        run("xcrun", "simctl", "io", udid, "screenshot", "--type=png", str(out))
        taken.append(out)
        print(f"  {scene}")
    run("xcrun", "simctl", "terminate", udid, BUNDLE, check=False, quiet=True)
    return taken


def shoot_maps(udid, out_dir, settle):
    """The payoff: the guide open in Apple Maps, in the device's language.

    Returns the path, or None with a reason printed. Whether a `?_col=` guide
    link opens a guide sheet in a *simulator* is genuinely unknown — on a device
    it does — so this is attempted and checked rather than assumed. The check is
    a baseline: Maps opened on a plain search, against Maps opened on the guide
    link. If the two frames are near enough identical, the guide did not open.
    """
    baseline = out_dir / "_maps-baseline.png"
    out = out_dir / f"{MAPS_SCENE}.png"

    run("xcrun", "simctl", "terminate", udid, "com.apple.Maps", check=False,
        quiet=True)
    run("xcrun", "simctl", "openurl", udid, "maps://?q=London", check=False)
    _sleep(settle + 4)
    run("xcrun", "simctl", "io", udid, "screenshot", "--type=png",
        str(baseline))

    run("xcrun", "simctl", "openurl", udid, GUIDE_URL, check=False)
    _sleep(settle + 6)
    run("xcrun", "simctl", "io", udid, "screenshot", "--type=png", str(out))
    run("xcrun", "simctl", "terminate", udid, "com.apple.Maps", check=False,
        quiet=True)

    if not out.exists():
        print(f"  {MAPS_SCENE}: no screenshot taken — skipped")
        baseline.unlink(missing_ok=True)
        return None
    delta = difference(baseline, out)
    baseline.unlink(missing_ok=True)
    # 6 is well above the noise of two map renders of the same city and well
    # below what a guide sheet covering the lower half of the screen produces.
    if delta < 6:
        print(f"  {MAPS_SCENE}: the guide did not open (delta {delta:.1f}) — "
              f"skipped, this locale gets {len(SCENES)} screenshots")
        out.unlink(missing_ok=True)
        return None
    print(f"  {MAPS_SCENE} (delta {delta:.1f})")
    return out


def _environ():
    import os
    return dict(os.environ)


def _sleep(seconds):
    import time
    time.sleep(seconds)


def verify(paths, locale, want):
    """Sizes, flat frames, and duplicates. Every one of these has bitten."""
    bad = []
    for p in paths:
        size = png_size(p)
        if size != want:
            bad.append(f"{p.name} is {size}, wanted {want[0]}x{want[1]}")
        flat = uniformity(p)
        if flat > 0.92:
            bad.append(f"{p.name} is {flat:.0%} one colour — the app probably "
                       f"never drew")
    seen = {}
    for p in paths:
        digest = hashlib.md5(p.read_bytes()).hexdigest()
        if digest in seen:
            bad.append(f"{p.name} is byte-identical to {seen[digest]} — two "
                       f"scenes rendered the same thing")
        seen[digest] = p.name
    if bad:
        print(f"\n{locale} FAILED verification:")
        for b in bad:
            print(f"  - {b}")
    return not bad


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--locale", help="one App Store locale, e.g. fr-FR")
    ap.add_argument("--no-maps", action="store_true",
                    help="skip the Apple Maps payoff shot")
    ap.add_argument("--settle", type=float, default=6.0,
                    help="seconds to wait after launch before the shutter")
    ap.add_argument("--keep-build", action="store_true",
                    help="reuse an existing build instead of rebuilding")
    args = ap.parse_args()

    check_scenes_agree()

    if not shutil.which("xcrun"):
        sys.exit("this needs macOS and Xcode — it drives xcrun simctl")

    wanted = ([t for t in SHOOT if t[0] == args.locale] if args.locale
              else SHOOT)
    if not wanted:
        sys.exit(f"{args.locale} is not one of: "
                 f"{', '.join(t[0] for t in SHOOT)}")

    app = ROOT / "build/ios/iphonesimulator/Runner.app"
    if not args.keep_build or not app.exists():
        print("building the screenshot app…")
        run("flutter", "build", "ios", "--simulator", "--debug",
            "--dart-define=WREN_SHOTS=true")
    if not app.exists():
        sys.exit(f"no app at {app}")

    udid, native, target = boot_simulator()
    print(f"all screenshots will be {target[0]}x{target[1]}")
    run("xcrun", "simctl", "install", udid, str(app))
    clean_status_bar(udid)

    failures, skipped_maps = [], []
    for asc, language, locale in wanted:
        print(f"\n{asc}")
        out_dir = SHOTS / asc / SLOT
        if out_dir.exists():
            shutil.rmtree(out_dir)
        out_dir.mkdir(parents=True)

        set_language(udid, language, locale)
        clean_status_bar(udid)
        paths = shoot_app(udid, out_dir, language, locale, args.settle)

        if not args.no_maps:
            maps = shoot_maps(udid, out_dir, args.settle)
            if maps:
                paths.append(maps)
            else:
                skipped_maps.append(asc)

        if native != target:
            for shot in paths:
                scale_to(shot, target)
        if not verify(paths, asc, target):
            failures.append(asc)

    print()
    if skipped_maps:
        print(f"no Maps shot for: {', '.join(skipped_maps)} — those locales "
              f"have {len(SCENES)} screenshots, not {len(SCENES) + 1}")
    if failures:
        sys.exit(f"verification failed for: {', '.join(failures)}")
    print(f"done — {len(wanted)} locales under {SHOTS}")


if __name__ == "__main__":
    main()
